### PR TITLE
Update graph class into LOL format

### PR DESCRIPTION
**Pull request by YuliTshuva**
Dear nmdp team,
Regarding the last pull request, here is a new improved one with all errors fixed.

### CODE REVIEW

**Review by pbashyal-nmdp — COMMENTED** [review]
If `networkx` is not used, please also remove from `requirements.txt`. Also looks like you have added `pandas` and `tqdm` as new dependencies,  please update the `requirements.txt`with those as well.

**Comment by pbashyal-nmdp** [comment]
Also, how did you validate that the change produces the same result as the networkx version. Are you able to add some automated tests ?

**Comment by YuliTshuva** [comment]
"""
Also, how did you validate that the change produces the same result as the
networkx version. Are you able to add some automated tests ?
"""
As a matter of fact, Sapir showed me some ways to check on an
enormous sized data and it seems perfectly fine.

As for the requirements.txt file, you are absolutely correct.
Thanks a lot and have a nice day,
Yuli.


‫בתאריך יום ה׳, 15 בפבר׳ 2024 ב-19:16 מאת ‪Pradeep Bashyal‬‏ <‪
***@***.***‬‏>:‬

**Comment by YuliTshuva** [comment]
Updating fork and sending a new pull request

**Pull request closed without merging**
